### ISSUE TITLE
When Facebook API is down or not responding, Mogli doesn't time out

### ISSUE THREAD

**Issue by ppetrick** [mmangino/mogli#57]
I took a quick look through the code to try and find a timeout option, but couldn't find one (although httparty does). Did I miss something?

**Comment by mmangino** [comment]
I don't use one. I would be happy to take a patch to add one.

**Comment by flipkick** [comment]
ok, this is no timeout option patch, but an easy patch if you need to define a timeout at the moment, in client.rb add an

default_timeout 5

after the "include HTTParty" line. And don't forget to handle the possible exceptions like Timeout::Error in your app.

5 seconds should be really enough. Otherwise it might block your web server instance for a long time. Many people coming to your site will result in a collapse of your site then, as we experienced yesterday. And at least we can't do all the graph api requests in background jobs, some have to be realtime.

**Comment by mmangino** [comment]
There are a bunch of calls that can take longer than 5 seconds and are done on the backend. I'm happy to take a patch that makes it configurable, but I've been using this code for quite a while without needing it, so I don't plan on doing the work.
